version: '3.9'

services:
  database:
    image: mysql
    platform: linux/x86_64
    container_name: ifilmes
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'ifilmes'
    ports:
      - '3306:3306'

  redis-server:
    restart: always
    image: redis:4.0
    container_name: redis-server
    command: /bin/bash -c 'redis-server --requirepass redispw'
    ports:
      - '6379:6379'